server:
  port: 8008

spring:
  application:
    name: ocean-sso-service
  profiles:
    active: dev
  main:
    banner-mode: 'OFF'
  jackson:
    serialization:
      indent-output: true

jvm_opts: -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx128m -Xmn64m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC


