server:
  port: 8008

spring:
  application:
    name: ocean-sso-service
  profiles:
    active: dev
  main:
    banner-mode: 'OFF'
  jackson:
    serialization:
      indent-output: true

httpclient:
  #defaultMaxPerRoute默认为2，maxTotal默认为20
  #连接池的最大连接数
  maxTotal: 300
  #每个route默认的最大连接数
  defaultMaxPerRoute: 100
  #建立连接超时
  connectTimeout: 1000000
  #等待连接超时
  connectionRequestTimeout: 5000000
  #从服务器读取超时
  socketTimeout: 100000000
  #连接状态验证
  staleConnectionCheckEnabled: true
  #validateAfterInactivity 空闲永久连接检查间隔，这个牵扯的还比较多
  #官方推荐使用这个来检查永久链接的可用性，而不推荐每次请求的时候才去检查
  validateAfterInactivity: 2000
  #  keyStorePath: C:/Users/Administrator/Desktop/广州办映射服务器测试证书20181010/dakehu/keystore.jks #证书路径
#  keyStorePath: /usr/https_cert/keystore.jks #证书路径
#  keyStorepass: 123456 #证书密码

jvm_opts: -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx128m -Xmn64m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC


